#!/usr/bin/env python3
"""Emit DRAM input + expected output for the T2 cooperative stress test.

T2 is a pure DMA echo: 8 input tiles flow DRAM → VMEM → DRAM, with
Saturn pounding bank 7 of VMEM in parallel. The "expected output" is
just the input (passthrough), since the test verifies memory traffic
integrity, not arithmetic.

Output: a C header with two arrays of 8 × 256 uint32 words (8 tiles ×
1024 bytes each). The host driver memcpys the input array to DRAM
before atlas_start() and compares the output region to the expected
array after halt.

Usage:
    python3 gen_saturn_atlas_8dma_rvv_vmem.py --out-header path/to/header.h
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

N_TILES = 8
TILE_BYTES = 1024
WORDS_PER_TILE = TILE_BYTES // 4
SEED = 0x8DA9CE5  # arbitrary fixed seed for reproducibility


def gen_input_tiles() -> list[list[int]]:
    rng = random.Random(SEED)
    tiles = []
    for t in range(N_TILES):
        # Mix the tile index into the stream so each tile has a
        # distinct, easily-recognised pattern in a hex dump.
        words = []
        for w in range(WORDS_PER_TILE):
            v = (rng.getrandbits(32) ^ ((t + 1) * 0x01010101)) & 0xFFFFFFFF
            words.append(v)
        tiles.append(words)
    return tiles


def emit_header(tiles: list[list[int]]) -> str:
    body = []
    body.append("/* Auto-generated by gen_saturn_atlas_8dma_rvv_vmem.py — DO NOT EDIT. */")
    body.append("#ifndef SATURN_ATLAS_8DMA_RVV_VMEM_GOLDEN_H")
    body.append("#define SATURN_ATLAS_8DMA_RVV_VMEM_GOLDEN_H")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append(f"#define SAS_8DMA_N_TILES         {N_TILES}")
    body.append(f"#define SAS_8DMA_TILE_BYTES      {TILE_BYTES}")
    body.append(f"#define SAS_8DMA_WORDS_PER_TILE  {WORDS_PER_TILE}")
    body.append("")
    body.append(
        "static const uint32_t sas_8dma_input_tiles"
        f"[SAS_8DMA_N_TILES][SAS_8DMA_WORDS_PER_TILE] = {{"
    )
    for t, words in enumerate(tiles):
        body.append(f"  /* tile {t} */ {{")
        for i in range(0, len(words), 8):
            chunk = words[i:i + 8]
            formatted = ", ".join(f"0x{w:08X}U" for w in chunk)
            body.append(f"    {formatted},")
        body.append("  },")
    body.append("};")
    body.append("")
    body.append(
        "/* Expected output = input (DMA passthrough echo). */"
    )
    body.append(
        "#define sas_8dma_expected_tiles sas_8dma_input_tiles"
    )
    body.append("")
    body.append("#endif /* SATURN_ATLAS_8DMA_RVV_VMEM_GOLDEN_H */")
    body.append("")
    return "\n".join(body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-header", required=True, type=Path,
                    help="Path to write the C header")
    args = ap.parse_args(argv)

    tiles = gen_input_tiles()
    text = emit_header(tiles)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(text)
    print(f"Wrote {N_TILES} tiles ({TILE_BYTES} B each) → {args.out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
