#!/usr/bin/env python3
"""Emit a C header containing an embedded Atlas kernel.

Usage:
    python3 gen_kernel_header.py <kernel.S> <name> <out.h>

Output:
    static const uint32_t kernel_<name>[] = {0x..., ...};
    #define KERNEL_<NAME>_LEN N

Used by the saturn-atlas cooperative stress tests so each `.S` kernel
is assembled at build time and pasted into the host driver. CMake
invokes this via `add_custom_command` and the host driver
`#include`s the produced `.h`. Single-script, no per-kernel wrappers.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_BAREMETAL_DIR = _HERE.parent
_ASSEMBLER = _BAREMETAL_DIR / "assembler.py"


def assemble_to_hex(asm_path: Path) -> list[int]:
    """Run assembler.py --out-hex and return the list of 32-bit words."""
    if not _ASSEMBLER.is_file():
        raise FileNotFoundError(f"assembler.py not found at {_ASSEMBLER}")
    with tempfile.NamedTemporaryFile(suffix=".hex", delete=False) as tmp:
        hex_path = Path(tmp.name)
    try:
        proc = subprocess.run(
            [sys.executable, str(_ASSEMBLER), str(asm_path),
             "--out-hex", str(hex_path)],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"assembler failed for {asm_path}: {proc.stderr.strip()}"
            )
        words = [int(line.strip(), 16) for line in hex_path.read_text().splitlines() if line.strip()]
    finally:
        hex_path.unlink(missing_ok=True)
    return words


def emit_header(name: str, words: list[int], asm_path: Path) -> str:
    """Render the C header text for the given kernel."""
    upper = name.upper()
    body = []
    body.append("/* Auto-generated by gen_kernel_header.py — DO NOT EDIT. */")
    body.append(f"/* Source: {asm_path.relative_to(asm_path.parents[3]) if len(asm_path.parts) >= 4 else asm_path} */")
    body.append(f"#ifndef KERNEL_{upper}_H")
    body.append(f"#define KERNEL_{upper}_H")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append(f"#define KERNEL_{upper}_LEN {len(words)}")
    body.append("")
    body.append(f"static const uint32_t kernel_{name}[KERNEL_{upper}_LEN] = {{")
    # 8 words per line for readability.
    for i in range(0, len(words), 8):
        chunk = words[i:i + 8]
        formatted = ", ".join(f"0x{w & 0xFFFFFFFF:08X}U" for w in chunk)
        comma = "," if i + len(chunk) < len(words) else ""
        body.append(f"    {formatted}{comma}")
    body.append("};")
    body.append("")
    body.append(f"#endif /* KERNEL_{upper}_H */")
    body.append("")
    return "\n".join(body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("asm", type=Path, help="Input .S file")
    ap.add_argument("name", help="Kernel name (lower-case identifier)")
    ap.add_argument("out", type=Path, help="Output .h path")
    args = ap.parse_args(argv)

    words = assemble_to_hex(args.asm)
    text = emit_header(args.name, words, args.asm)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"Wrote {len(words)} words → {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
