#!/usr/bin/env python3
"""Emit DRAM input + expected output tiles for the T4 cooperative test.

T4 is structurally a DMA echo (same as T2): 8 input tiles flow DRAM →
VMEM → DRAM, with Saturn pounding its OWN large DRAM-backed scratch
buffer concurrently. Saturn's buffer is host-managed (no golden
emitted here); this generator only covers the Atlas DMA tiles.

Output: a C header with two arrays of 8 × 256 uint32 words. The host
driver memcpys the input array to DRAM before atlas_start() and
compares the output region post-halt.

Usage:
    python3 gen_saturn_atlas_dmem_sbus_dma.py --out-header path/to/header.h
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

N_TILES = 8
TILE_BYTES = 1024
WORDS_PER_TILE = TILE_BYTES // 4
SEED = 0xD3E12B05


def gen_input_tiles() -> list[list[int]]:
    rng = random.Random(SEED)
    tiles = []
    for t in range(N_TILES):
        words = []
        for w in range(WORDS_PER_TILE):
            v = (rng.getrandbits(32) ^ ((t + 1) * 0x6A09E667)) & 0xFFFFFFFF
            words.append(v)
        tiles.append(words)
    return tiles


def emit_header(tiles: list[list[int]]) -> str:
    body = []
    body.append("/* Auto-generated by gen_saturn_atlas_dmem_sbus_dma.py — DO NOT EDIT. */")
    body.append("#ifndef SATURN_ATLAS_DMEM_SBUS_DMA_GOLDEN_H")
    body.append("#define SATURN_ATLAS_DMEM_SBUS_DMA_GOLDEN_H")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append(f"#define SAS_DMEM_N_TILES         {N_TILES}")
    body.append(f"#define SAS_DMEM_TILE_BYTES      {TILE_BYTES}")
    body.append(f"#define SAS_DMEM_WORDS_PER_TILE  {WORDS_PER_TILE}")
    body.append("")
    body.append(
        "static const uint32_t sas_dmem_input_tiles"
        f"[SAS_DMEM_N_TILES][SAS_DMEM_WORDS_PER_TILE] = {{"
    )
    for t, words in enumerate(tiles):
        body.append(f"  /* tile {t} */ {{")
        for i in range(0, len(words), 8):
            chunk = words[i:i + 8]
            formatted = ", ".join(f"0x{w:08X}U" for w in chunk)
            body.append(f"    {formatted},")
        body.append("  },")
    body.append("};")
    body.append("")
    body.append("/* Expected DMA output = input (echo). */")
    body.append("#define sas_dmem_expected_tiles sas_dmem_input_tiles")
    body.append("")
    body.append("#endif /* SATURN_ATLAS_DMEM_SBUS_DMA_GOLDEN_H */")
    body.append("")
    return "\n".join(body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-header", required=True, type=Path)
    args = ap.parse_args(argv)

    tiles = gen_input_tiles()
    text = emit_header(tiles)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(text)
    print(f"Wrote {N_TILES} tiles ({TILE_BYTES} B each) → {args.out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
