#!/usr/bin/env python3
"""Emit DRAM input + LSU init pattern for the T1 cooperative stress test.

T1 has three disjoint sub-regions in VMEM bank 3:
  - LSU sub-region: pre-loaded by the host with a known pattern;
    Atlas's VLOAD/VSTORE identity loop preserves it.
  - DMA sub-region: receives DRAM IN tile via DMA.LOAD, then DMA.STORE
    echoes it to DRAM OUT.
  - Saturn sub-region: zeroed initially; Saturn RVV sweep accumulates
    iter values (handled by the host driver, no golden needed here).

The two patterns this generator emits are 256 words (1024 B) each:
  sas_3way_dma_input_tile   — IN tile pattern (echoed by DMA round trip).
  sas_3way_lsu_init_pattern — LSU sub-region pre-load (preserved by
                              identity loop; host re-reads VMEM after halt).

Usage:
    python3 gen_saturn_atlas_vmem_3way_arb.py --out-header path/to/header.h
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

WORDS_PER_TILE = 256       # 1024 B / 4 B per word
SEED = 0x3A1AB1A           # arbitrary fixed seed


def gen_pattern(salt: int, count: int) -> list[int]:
    rng = random.Random(SEED ^ (salt * 0x9E3779B1))
    return [rng.getrandbits(32) for _ in range(count)]


def emit_header(dma_input: list[int], lsu_init: list[int]) -> str:
    body = []
    body.append("/* Auto-generated by gen_saturn_atlas_vmem_3way_arb.py — DO NOT EDIT. */")
    body.append("#ifndef SATURN_ATLAS_VMEM_3WAY_ARB_GOLDEN_H")
    body.append("#define SATURN_ATLAS_VMEM_3WAY_ARB_GOLDEN_H")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append(f"#define SAS_3WAY_WORDS_PER_TILE  {WORDS_PER_TILE}")
    body.append(f"#define SAS_3WAY_TILE_BYTES      {WORDS_PER_TILE * 4}")
    body.append("")

    def emit_array(name: str, words: list[int]) -> None:
        body.append(f"static const uint32_t {name}[SAS_3WAY_WORDS_PER_TILE] = {{")
        for i in range(0, len(words), 8):
            chunk = words[i:i + 8]
            formatted = ", ".join(f"0x{w:08X}U" for w in chunk)
            body.append(f"    {formatted},")
        body.append("};")
        body.append("")

    emit_array("sas_3way_dma_input_tile", dma_input)
    emit_array("sas_3way_lsu_init_pattern", lsu_init)
    body.append("/* Expected DMA output = input (DMA round-trip echo). */")
    body.append("#define sas_3way_dma_expected_tile sas_3way_dma_input_tile")
    body.append("")
    body.append("#endif /* SATURN_ATLAS_VMEM_3WAY_ARB_GOLDEN_H */")
    body.append("")
    return "\n".join(body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-header", required=True, type=Path)
    args = ap.parse_args(argv)

    dma_input = gen_pattern(salt=1, count=WORDS_PER_TILE)
    lsu_init  = gen_pattern(salt=2, count=WORDS_PER_TILE)
    text = emit_header(dma_input, lsu_init)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(text)
    print(f"Wrote DMA input + LSU init ({WORDS_PER_TILE} words each) → {args.out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
