#!/usr/bin/env python3
"""Emit DRAM input tiles + LSU/scalar pre-fill patterns for the
4-rung 2-bank arb cooperative test.

Patterns:
  - sas_4rung_dma_input_b3: 256 32-bit words (1 KiB), DMA tile for
    bank 3. Atlas DMA does load -> store round-trip; expected DRAM
    OUT == this.
  - sas_4rung_dma_input_b4: 256 32-bit words (1 KiB), DMA tile for
    bank 4. Same shape as bank 3 but different content.
  - sas_4rung_lsu_init_b3: 256 32-bit words (1 KiB), pre-load for
    bank 3 vector LSU sub-region. The Atlas kernel's VLOAD/VSTORE
    identity loop preserves it; final state must match.
  - sas_4rung_scalar_init_b4: 256 32-bit words (1 KiB), pre-load for
    bank 4 scalar LSU sub-region. The kernel reads words at byte
    offsets 0 and 4 (i.e. scalar_init[0] and [1]) and writes them at
    byte offsets 8 and 12 (load-result-consumed pattern: the SW
    forces the LW to retire). Bytes 0,4 stay untouched; bytes 8,12
    get overwritten.

Usage:
    python3 gen_saturn_atlas_4rung_2bank_arb.py --out-header path/to/header.h
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

WORDS_PER_TILE = 256        # 1 KiB / 4 B
SEED = 0x4A2BA1AB


def gen_pattern(salt: int) -> list[int]:
    rng = random.Random(SEED ^ (salt * 0x9E3779B1))
    return [rng.getrandbits(32) for _ in range(WORDS_PER_TILE)]


def emit_array(name: str, words: list[int], out: list[str]) -> None:
    out.append(f"static const uint32_t {name}[SAS_4RUNG_WORDS_PER_TILE] = {{")
    for i in range(0, len(words), 8):
        chunk = words[i:i + 8]
        formatted = ", ".join(f"0x{w:08X}U" for w in chunk)
        out.append(f"    {formatted},")
    out.append("};")
    out.append("")


def emit_header(
    dma_b3: list[int],
    dma_b4: list[int],
    lsu_init: list[int],
    scalar_init: list[int],
) -> str:
    body: list[str] = []
    body.append("/* Auto-generated by gen_saturn_atlas_4rung_2bank_arb.py - DO NOT EDIT. */")
    body.append("#ifndef SATURN_ATLAS_4RUNG_2BANK_ARB_GOLDEN_H")
    body.append("#define SATURN_ATLAS_4RUNG_2BANK_ARB_GOLDEN_H")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append(f"#define SAS_4RUNG_WORDS_PER_TILE  {WORDS_PER_TILE}")
    body.append(f"#define SAS_4RUNG_TILE_BYTES      {WORDS_PER_TILE * 4}")
    body.append("")
    emit_array("sas_4rung_dma_input_b3", dma_b3, body)
    emit_array("sas_4rung_dma_input_b4", dma_b4, body)
    emit_array("sas_4rung_lsu_init_b3", lsu_init, body)
    emit_array("sas_4rung_scalar_init_b4", scalar_init, body)
    body.append("/* Atlas DMA does load -> store round-trip; expected DRAM OUT = input. */")
    body.append("#define sas_4rung_dma_expected_b3 sas_4rung_dma_input_b3")
    body.append("#define sas_4rung_dma_expected_b4 sas_4rung_dma_input_b4")
    body.append("")
    body.append("#endif /* SATURN_ATLAS_4RUNG_2BANK_ARB_GOLDEN_H */")
    body.append("")
    return "\n".join(body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-header", required=True, type=Path)
    args = ap.parse_args(argv)

    dma_b3 = gen_pattern(salt=1)
    dma_b4 = gen_pattern(salt=2)
    lsu_init = gen_pattern(salt=3)
    scalar_init = gen_pattern(salt=4)

    text = emit_header(dma_b3, dma_b4, lsu_init, scalar_init)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(text)
    print(f"Wrote 4 patterns ({WORDS_PER_TILE} words each) -> {args.out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
