/*
InnerProductTreesVectorTest.scala - Data-driven MXU tests from Python-generated vectors.

Reads test vectors from src/test/resources/mxu_vectors.txt (generated by
gen_mxu_vectors.py) and drives the InnerProductTrees with fractional FP values.

Generate vectors first: in sp26-atlas-acc
  python3 scripts/gen_mxu_vectors.py --out src/test/resources/mxu_vectors.txt

Run:
  mill atlas.test.testOnly atlas.ipt.InnerProductTreesVectorTest

Comparison uses ONLY absolute + relative error tolerances (no ULP metric).

Tolerances:
- absTolerance: treat both |value| <= absTolerance (in BF16 magnitude bits) as equal
- relTolerance: non-symmetric relative error threshold: |a-e| / max(|e|, eps)
*/

package atlas.ipt

import chisel3._
import chisel3.simulator.EphemeralSimulator._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.Outcome
import atlas.common.InnerProductTreeParams
import scala.io.Source
import scala.collection.mutable.ArrayBuffer

class InnerProductTreesVectorTest extends AnyFlatSpec with Matchers {

  //----------- CI/CD INCLUDE --------------
  override def withFixture(test: NoArgTest): Outcome = {
    val outcome = super.withFixture(test)
    if (outcome.isFailed) {
      println("InnerProductTreesVectorTest=FAILED")
    } else if (outcome.isSucceeded) {
      println("InnerProductTreesVectorTest=PASSED")
    }
    outcome
  }
  //----------- CI/CD INCLUDE --------------

  // Configuration
  val vectorResource = "/mxu_vectors.txt"

  // Tolerances:
  // - absTolerance: treat both |value| <= absTolerance (in BF16 magnitude bits) as equal
  // - relTolerance: non-symmetric relative error threshold: |a-e| / max(|e|, eps)
  val absTolerance = 0x0040
  val relTolerance = 0.01
  val relEps       = 1e-8

  // Test vector data class
  case class TestVector(
    id:       Int,
    caseType: String,
    sel:      Int,
    act:      Seq[Int],
    weights:  Seq[Seq[Int]], // numLanes x vecLen
    bias:     Seq[Int],
    psum:     Seq[Int],
    expected: Seq[Int],
  )

  // Parser for the flat hex format
  //
  //   # <id> <type>
  //   sel <n>
  //   act <hex> <hex> ...
  //   wgt <r> <hex> <hex> ...    (repeated per lane)
  //   bias <hex> <hex> ...
  //   psum <hex> <hex> ...
  //   exp <hex> <hex> ...

  def hexToInt(h: String): Int = Integer.parseUnsignedInt(h, 16)

  def loadVectors(resourcePath: String): Seq[TestVector] = {
    val stream = getClass.getResourceAsStream(resourcePath)
    require(
      stream != null,
      s"Resource '$resourcePath' not found on classpath. Run: python3 scripts/gen_mxu_vectors.py --out src/test/resources${resourcePath}",
    )
    val src = Source.fromInputStream(stream)
    val vectors = ArrayBuffer[TestVector]()

    var id       = 0
    var caseType = ""
    var sel      = 0
    var act      = Seq.empty[Int]
    var weights  = ArrayBuffer[Seq[Int]]()
    var bias     = Seq.empty[Int]
    var psum     = Seq.empty[Int]
    var expected = Seq.empty[Int]
    var inCase   = false

    def flush(): Unit = {
      if (inCase) {
        vectors += TestVector(id, caseType, sel, act, weights.toSeq, bias, psum, expected)
        weights = ArrayBuffer[Seq[Int]]()
        inCase = false
      }
    }

    try {
      for (raw <- src.getLines()) {
        val line = raw.trim
        if (line.isEmpty) {
          flush()
        } else if (line.startsWith("#")) {
          flush()
          val parts = line.drop(1).trim.split("\\s+")
          id = parts(0).toInt
          caseType = if (parts.length > 1) parts(1) else "unknown"
          inCase = true
        } else {
          val parts = line.split("\\s+")
          parts(0) match {
            case "sel"  => sel = parts(1).toInt
            case "act"  => act = parts.drop(1).map(hexToInt).toSeq
            case "wgt"  => weights += parts.drop(2).map(hexToInt).toSeq
            case "bias" => bias = parts.drop(1).map(hexToInt).toSeq
            case "psum" => psum = parts.drop(1).map(hexToInt).toSeq
            case "exp"  => expected = parts.drop(1).map(hexToInt).toSeq
            case _      =>
          }
        }
      }
      flush()
    } finally {
      src.close()
    }

    vectors.toSeq
  }

  // BF16 helpers
  def bf16BitsToFloat(bits: Int): Float = {
    val fp32Bits = (bits & 0xFFFF) << 16
    java.lang.Float.intBitsToFloat(fp32Bits)
  }

  case class Errs(absErr: Double, relErr: Double)

  // BF16 comparison using ONLY abs + relative tolerances (no ULP)
  //
  // Pass if ANY is true:
  //   1) both values are near zero in BF16 magnitude-bits space (<= absTolerance)
  //   2) relative error <= relTolerance, where:
  //        relErr = |a-e| / max(|e|, eps)
  //
  // Returns: (ok, Errs)
  def bf16WithinTolerance(a16: Int, e16: Int): (Boolean, Errs) = {
    val aMag = a16 & 0x7FFF
    val eMag = e16 & 0x7FFF

    // check 1: both near zero in BF16 magnitude bits
    if (aMag <= absTolerance && eMag <= absTolerance) {
      return (true, Errs(0.0, 0.0))
    }

    val a = bf16BitsToFloat(a16).toDouble
    val e = bf16BitsToFloat(e16).toDouble

    val absErr = math.abs(a - e)
    val denom  = math.max(math.abs(e), relEps)
    val relErr = absErr / denom

    (relErr <= relTolerance, Errs(absErr, relErr))
  }

  def selToEnum(sel: Int): AddendSel.Type = {
    sel match {
      case 0 => AddendSel.UseAct
      case 1 => AddendSel.UseBias
      case 2 => AddendSel.UsePsum
      case _ => AddendSel.UseAct
    }
  }

  // Test helpers
  def idle(dut: InnerProductTrees, p: InnerProductTreeParams): Unit = {
    dut.io.compute.valid.poke(false.B)
    dut.io.weightLoad.valid.poke(false.B)
    for (j <- 0 until p.vecLen) dut.io.compute.bits.act(j).poke(0.U)
    for (r <- 0 until p.numLanes) {
      dut.io.compute.bits.bias(r).poke(0.U)
      dut.io.compute.bits.psum(r).poke(0.U)
    }
    dut.io.compute.bits.addendSel.poke(AddendSel.UseAct)
    dut.io.weightLoad.bits.weightSel.poke(WeightSel.UseTr)
    dut.io.weightLoad.bits.laneIdx.poke(0.U)
    dut.io.weightLoad.bits.last.poke(false.B)
    for (c <- 0 until p.vecLen) {
      dut.io.weightLoad.bits.weightsDma(c).poke(0.U)
      dut.io.weightLoad.bits.weightsTr(c).poke(0.U)
    }
  }

  def waitForResult(dut: InnerProductTrees, p: InnerProductTreeParams): Unit = {
    if (p.latency > 1) dut.clock.step(p.latency - 1)
  }

  // Test body
  "InnerProductTrees" should "match Python ground truth for fractional FP vectors" in {
    val p = InnerProductTreeParams()
    val vectors = loadVectors(vectorResource)
    require(vectors.nonEmpty, "No test vectors found. Run gen_mxu_vectors.py first.")

    simulate(new InnerProductTrees(p)) { dut =>
      var passed = 0
      var failed = 0

      // hardcoded
      val outFile =
        new java.io.PrintWriter("../../../../../src/test/resources/rtl_vector_outputs.txt") // path is chipyard/generators/sp26-atlas-acc/src/test/resources
      outFile.println("# case_id case_type        lane actual_hex expected_hex  actual_float expected_float abs_err rel_err match")

      for (tv <- vectors) {
        idle(dut, p)

        // load weights one lane at a time via weightsTr (weightSel = UseTr)
        dut.io.weightLoad.valid.poke(true.B)
        dut.io.weightLoad.bits.weightSel.poke(WeightSel.UseTr)
        for (r <- 0 until p.numLanes) {
          dut.io.weightLoad.bits.laneIdx.poke(r.U)
          dut.io.weightLoad.bits.last.poke((r == p.numLanes - 1).B)
          for (c <- 0 until p.vecLen) {
            dut.io.weightLoad.bits.weightsTr(c).poke(tv.weights(r)(c).U)
            dut.io.weightLoad.bits.weightsDma(c).poke(0.U)
          }
          dut.clock.step()
        }
        dut.io.weightLoad.valid.poke(false.B)

        // fire compute
        dut.io.compute.valid.poke(true.B)
        for (j <- 0 until p.vecLen)
          dut.io.compute.bits.act(j).poke(tv.act(j).U)
        for (r <- 0 until p.numLanes) {
          dut.io.compute.bits.bias(r).poke(tv.bias(r).U)
          dut.io.compute.bits.psum(r).poke(tv.psum(r).U)
        }
        dut.io.compute.bits.addendSel.poke(selToEnum(tv.sel))
        dut.clock.step()
        dut.io.compute.valid.poke(false.B)

        waitForResult(dut, p)

        // check outputs
        dut.io.out.valid.expect(true.B)
        var caseOk = true
        for (r <- 0 until p.numLanes) {
          val actual   = dut.io.out.bits(r).peek().litValue
          val expected = tv.expected(r)

          val a16 = actual.toInt & 0xFFFF
          val e16 = expected & 0xFFFF

          val aFloat = bf16BitsToFloat(a16)
          val eFloat = bf16BitsToFloat(e16)

          val (ok, errs) = bf16WithinTolerance(a16, e16)

          outFile.println(
            f"${tv.id}%8d ${tv.caseType}%-16s $r%4d   0x${a16}%04x       0x${e16}%04x " +
              f"$aFloat%14.6g $eFloat%14.6g ${errs.absErr}%10.6g ${errs.relErr}%10.6g ${if (ok) "PASS" else "FAIL"}"
          )

          if (!ok) {
            caseOk = false
            println(
              f"  FAIL row ${tv.id} lane $r: got 0x${a16}%04x ($aFloat%.6g) " +
                f"exp 0x${e16}%04x ($eFloat%.6g) " +
                f"[absErr=${errs.absErr}%.6g relErr=${errs.relErr}%.6g] " +
                f"(tol: abs<=0x${absTolerance}%04x rel<${relTolerance}%.5f)"
            )
          }
        }

        if (caseOk) passed += 1 else failed += 1
      }

      outFile.close()
      println(s"\nWrote sp26-atlas-acc/src/test/resources/rtl_vector_outputs.txt")
      println(s"Vector test results: $passed passed, $failed failed out of ${vectors.length}")
      failed shouldBe 0
    }
  }
}
