"""LUT source-of-truth ports for the Atlas vector engine.

The Chisel source for the LUT-backed transcendentals lives in
`dependencies/sp26-fp-units/.../vpuLUTs/{Rcp,Sqrt,Log,SinCos,Ex,Tanh}LUT.scala`
and `LUTParams.scala`. Each LUT is generated by Scala-side
`VecInit.tabulate(entries) { i => round(f(i) * 2^n) }` at hardware
elaboration time. The ports here are the bit-equivalent Python
implementations of those generators and the per-lane formatters
(`lutFixedToBf16Rcp`, `lutFixedToBf16Sqrt`, `lutFixedToBf16Log`,
`lutFixedToBf16`, `bf16ToQmnTimesTwoOverPi`).

Layout:
  - `lut_params.py`  → bit-exact ports of `trait LUTParams` and the
                       `HasSinCosParams` helpers.
  - `lut_tables.py`  → table generators that mirror the
                       `VecInit.tabulate` formulas; each module's
                       `__init__` consumes them once and caches the list.

Both lane_boxes and tests import from here; if you change a Scala
LUT formula, change the Python copy in the same commit and the bit-
exact tests will catch any drift.
"""
