#!/usr/bin/env bash
#
# Run the vector-engine test suite sequentially (mill does not support
# concurrent test runs). Each result is tracked and summarised at the end.
#
# The six VectorEngineTop<Family>VectorTest classes load per-family golden
# vectors from src/test/resources/vpu_test_vectors/vpu_<family>_vectors.txt.
# Those files are generated by scripts/gen_vpu_test_vectors.py. This script
# regenerates them up-front so the tests never hit the "Resource not found"
# require() fallback. Set REGEN=1 to force a refresh even when the files
# already exist.
#
# After the Scala tests run, the pytest drift guard
# baremetal/generators/software_models/vpu/tests/test_rtl_actual_outputs.py
# cross-checks the Python funct model against the RTL snapshot that each
# family test just wrote back out to disk.
#
# NOTE: All test classes below live in package `atlas.vector` regardless of
# their source subdirectory (RcpSqrtTest/, vectorFSM/, or flat). The list is
# alphabetized to match the output of
#   grep -rE '^class\s+\w+\s+extends\s+AnyFlatSpec' src/test/scala/atlas/vector
# If you add a new AnyFlatSpec test under src/test/scala/atlas/vector, add
# its class name here.
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VECTOR_DIR="$REPO_DIR/src/test/resources/vpu_test_vectors"
GEN_SCRIPT="$SCRIPT_DIR/gen_vpu_test_vectors.py"
PYTEST_DRIFT="baremetal/generators/software_models/vpu/tests/test_rtl_actual_outputs.py"

FAMILIES=(binary unary_simple unary_math row_reduce col_reduce vli)

if [ ! -f "$GEN_SCRIPT" ]; then
  echo "ERROR: missing vector generator at $GEN_SCRIPT" >&2
  exit 1
fi

mkdir -p "$VECTOR_DIR"

need_regen=0
if [ -n "${REGEN:-}" ]; then
  need_regen=1
else
  for fam in "${FAMILIES[@]}"; do
    if [ ! -f "$VECTOR_DIR/vpu_${fam}_vectors.txt" ]; then
      need_regen=1
      break
    fi
  done
fi

echo "== Preparing VPU golden vectors"
if [ $need_regen -eq 1 ]; then
  echo "  regenerating per-family vectors via gen_vpu_test_vectors.py..."
  ( cd "$REPO_DIR" && python3 "$GEN_SCRIPT" ) \
    || { echo "ERROR: failed to generate vpu vectors" >&2; exit 1; }
else
  echo "  per-family vectors present (REGEN=1 to force refresh)"
fi

TESTS=(
  AddSubSumTest
  DivSqrtBlockTest
  FSMDouble
  FSMDoubleTransition
  FSMSingle
  FSMSingleTransition
  LogLUTTest
  MaxReduBlockTest
  PairwiseMaxTest
  PairwiseMinTest
  RVAddSubTest
  RVDivSqrtTest
  RVExpTest
  RVFP8PackTest
  RVFP8UnpackTest
  RVLog2Test
  RVMulTest
  RVSinCosTest
  RVSqCbTest
  RVTanhTest
  RVVLITest
  RcpLUTTest
  RcpTest
  ReduSumBlockTest
  ReluBlockTest
  RowMaxTest
  RowMinTest
  SqrtLUTTest
  SqrtTest
  TanhBlockTest
  VETUnitTesting
  VectorEngineRawCsumSmokeTest
  VectorEngineTopBinaryVectorTest
  VectorEngineTopColReduceVectorTest
  VectorEngineTopRowReduceVectorTest
  VectorEngineTopTest
  VectorEngineTopUnaryMathVectorTest
  VectorEngineTopUnarySimpleVectorTest
  VectorEngineTopVLIVectorTest
)

declare -A RESULTS
START_ALL=$(date +%s)

for t in "${TESTS[@]}"; do
  echo
  echo "======================================================================"
  echo "== RUNNING: atlas.vector.$t"
  echo "== $(date '+%Y-%m-%d %H:%M:%S')"
  echo "======================================================================"
  START=$(date +%s)
  mill atlas.test.testOnly atlas.vector.$t
  rc=$?
  END=$(date +%s)
  DURATION=$((END - START))
  if [ $rc -eq 0 ]; then
    RESULTS[$t]="PASS  (${DURATION}s)"
  else
    RESULTS[$t]="FAIL rc=$rc  (${DURATION}s)"
  fi
done

# ── pytest drift guard ──
echo
echo "======================================================================"
echo "== RUNNING: pytest $PYTEST_DRIFT"
echo "== $(date '+%Y-%m-%d %H:%M:%S')"
echo "======================================================================"
PY_START=$(date +%s)
( cd "$REPO_DIR" && PYTHONPATH=baremetal/generators python3 -m pytest "$PYTEST_DRIFT" )
py_rc=$?
PY_END=$(date +%s)
PY_DURATION=$((PY_END - PY_START))
if [ $py_rc -eq 0 ]; then
  RESULTS[pytest_drift_guard]="PASS  (${PY_DURATION}s)"
else
  RESULTS[pytest_drift_guard]="FAIL rc=$py_rc  (${PY_DURATION}s)"
fi

END_ALL=$(date +%s)
TOTAL=$((END_ALL - START_ALL))

echo
echo "======================================================================"
echo "== SUMMARY  (total: ${TOTAL}s)"
echo "======================================================================"
FAIL_COUNT=0
for t in "${TESTS[@]}"; do
  printf "  %-40s %s\n" "$t" "${RESULTS[$t]}"
  case "${RESULTS[$t]}" in FAIL*) FAIL_COUNT=$((FAIL_COUNT+1));; esac
done
printf "  %-40s %s\n" "pytest_drift_guard" "${RESULTS[pytest_drift_guard]}"
case "${RESULTS[pytest_drift_guard]}" in FAIL*) FAIL_COUNT=$((FAIL_COUNT+1));; esac
TOTAL_COUNT=$(( ${#TESTS[@]} + 1 ))
echo "----------------------------------------------------------------------"
if [ $FAIL_COUNT -eq 0 ]; then
  echo "  all ${TOTAL_COUNT} tests passed"
  exit 0
else
  echo "  ${FAIL_COUNT} of ${TOTAL_COUNT} tests FAILED"
  exit 1
fi
